name: Deploy to GitHub pages
on: 
  push:
    branches:
    - main
    
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout Branch
        uses: actions/checkout@v4

      - name: Git Add and Commit
        run: |
            git config --global user.name 'Yogesh Choudhary Paliyal'
            git config --global user.email 'yogeshpaliyal@users.noreply.github.com'
      
      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
        
      - name: Install dependencies
        run: bun install

      - name: Build bundle
        id: build-bundle
        run: bun run build

      - name: Expors Build to Github Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
      
